from turtle import *
from time import *

# Mengatur ukuran dan posisi layar utama
setup(500,500)
speed(5)
bgcolor("black")
shape("turtle")

def drawRounds(size, filled):
    pendown()
    if filled == True:
        begin_fill()
        setheading(180)
        circle(size, 360)
        if filled == True:
            end_fill()

def drawRect(length, width, filled):
    pendown()
    if filled == True:
        begin_fill()
    forward(length)
    right(90)
    forward(width)
    right(90)
    forward(length)
    right(90)
    forward(width)
    if filled == True:
        end_fill()

def head():
    color("blue", "blue")
    penup()
    goto(0,100)
    drawRounds(75,True) 
    color('white', "white")
    penup()
    goto(0,72)
    drawRounds(60,True)

def eye():
    color('black', 'white')
    penup()
    goto(-15,80)
    drawRounds(17,True)
    color('black', 'white')
    penup()
    goto(19,80)
    drawRounds(17,True)
    color('black', 'black')
    penup()
    goto(-8,70)
    drawRounds(6,True)
    color('white', 'white')
    penup()
    goto(-8,66)
    drawRounds(2,True)
    color('black', 'black')
    penup()
    goto(12,70)
    drawRounds(6,True)
    color('white', 'white')
    penup()
    goto(12,66)
    drawRounds(2,True)

def nose():
    color('red', 'red')
    penup()
    goto(0,40)
    drawRounds(7,True)

def mouth():
    color('black', 'black')
    penup()
    goto(-30,-20)
    pendown()
    setheading(-27)
    circle(70,55)
    penup()
    goto(0,26)
    pendown()
    goto(0,-25)

def whiskers():
    color('black', 'black')
    penup()
    goto(10,5)
    pendown()
    goto(-40,5)
    penup()
    goto(10,5)
    pendown()
    goto(40,5)
    penup()
    goto(-10,15)
    pendown()
    goto(-40,20)
    penup()
    goto(10,15)
    pendown()
    goto(40,20)
    penup()
    goto(-10,-5)
    pendown()
    goto(-40,-10)
    penup()
    goto(10,-5)
    pendown()
    goto(40,-10)

def body():
    penup()
    goto(0,-35)
    color('blue', 'blue')
    drawRounds(50,True)
    penup()
    penup()
    goto(0,-35)
    color('white', 'white')
    drawRounds(40,True)
    color('red', 'red')
    penup()
    goto(35,-30) ###
    drawRect(80,10,True)
    color('white', 'white')
    penup()
    goto(15,-127)
    pendown()
    setheading(90)
    begin_fill()
    circle(14,180)
    end_fill()

def legs():
    color('black', 'white')
    penup()
    goto(-30,-110)
    drawRounds(20,True)
    color('black', 'white')
    penup()
    goto(30,-110)
    drawRounds(20,True)

def arms():
    color('blue', 'blue')
    penup()
    begin_fill()
    goto(-51,-50)
    pendown()
    goto(-51,-75)
    left(70)
    goto(-51,-75)
    left(70)
    goto(-76,-85)
    left(70)
    goto(-86,-70)
    left(70)
    goto(-51,-50)
    end_fill()
    color('blue', 'blue')
    penup()
    begin_fill()
    goto(49,-50)
    pendown()
    goto(49,-75)
    left(70)
    goto(74,-85)
    left(70)
    goto(84,-70)
    left(70)
    goto(49,-50)
    end_fill()

def bell():
    color('yellow', 'yellow')
    penup()
    goto(0,-41)
    drawRounds(8,True)
    color('black', 'black')
    penup()
    goto(5, -47)
    drawRect(10,4,False)
    color('black', 'black')
    penup()
    goto(0, -53)
    drawRounds(2,True)

def hands():
    color('black', 'white')
    penup()
    goto(-90, -71)
    drawRounds(15,True)
    color('black', 'white')
    penup()
    goto(90, -71)
    drawRounds(15,True)
    
def kantong():
    color('black', 'black')
    penup()
    goto(-25, -70)
    pendown()
    setheading(-90)
    circle(25,180)
    goto(-25,-70)
    hideturtle()

head()
eye()
nose()
mouth()
whiskers()
body()
legs()
arms()
hands()
bell()
kantong()
sleep(5)