import turtle
import time
tr = turtle.Turtle()
tr.speed("fastest")
tr.up()

for i in range(10): #Hiasan kiri
    for j in range(2):
        tr.pensize(6)
        tr.goto(-500,0)
        tr.down()
        tr.color("purple")
        tr.forward(100)
        tr.circle(5, steps=4)
        tr.right(60)
        tr.color("violet")
        tr.forward(50)
        tr.right(120)
    tr.right(30)
tr.up()

for i in range(10): #Hiasan kanan
    for j in range(2):
        tr.pensize(6)
        tr.goto(500, 0)
        tr.down()
        tr.color("red")
        tr.forward(100)
        tr.circle(5, steps=4)
        tr.right(60)
        tr.color("crimson")
        tr.forward(50)
        tr.right(120)
    tr.right(30)
tr.up()

for i in range(1): #Bulan
    tr.pensize(6)
    tr.goto(60, 165)
    tr.down()
    tr.color("yellow")
    tr.begin_fill()
    tr.circle(200)
    tr.end_fill()
tr.up()

for i in range(1): #Bulan
    tr.pensize(6)
    tr.goto(110, 165)
    tr.down()
    tr.color("white")
    tr.begin_fill()
    tr.circle(200)
    tr.end_fill()
tr.up()
for i in range(10): #Hiasan bawah
    for j in range(2):
        tr.pensize(6)
        tr.goto(20, -265)
        tr.down()
        tr.color("dark turquoise")
        tr.forward(100)
        tr.circle(5, steps=4)
        tr.right(60)
        tr.color("cyan")
        tr.forward(50)
        tr.right(120)
    tr.right(30)

turtle.up()
turtle.color("red")
turtle.goto(-290, 40)
turtle.write("Selamat", font=(None, 40))
turtle.goto(-60,40)
turtle.color("purple")
turtle.write("Berbuka", font=(None, 40))
turtle.goto(145,40)
turtle.color('blue')
turtle.write("Puasa", font=(None, 40))
turtle.goto(-300,-60)
turtle.color('green')
turtle.write("4 Ramadhan 1444 H", font=(None, 50))
turtle.done()
time.sleep(5)